const CALC_OPERATION = {
    ONE: 'ONE',
    TWO: 'TWO',
    THREE: 'THREE',
    FOUR: 'FOUR',
    FIVE: 'FIVE',
    SIX: 'SIX',
    SEVEN: 'SEVEN',
    EIGHT: 'EIGHT',
    NINE: 'NINE',
    ZERO: 'ZERO',
    DECIMAL: 'DECIMAL',
    PI: 'PI',
    E: 'E',
    X: 'X',
    Y: 'Y',
    Z: 'Z',
    OPEN_PAREN: 'OPEN_PAREN',
    CLOSE_PAREN: 'CLOSE_PAREN',
    RAISE_TEN: 'RAISE_TEN',
    MOD: 'MOD',
    DIVIDE: 'DIVIDE',
    MULTIPLY: 'MULTIPLY',
    SUBTRACT: 'SUBTRACT',
    ADD: 'ADD',
    POWER_NEGATIVE_ONE: 'POWER_NEGATIVE_ONE',
    POWER_Y: 'POWER_Y',
    POWER_TWO: 'POWER_TWO',
    SQUARE_ROOT: 'SQUARE_ROOT',
    FACTORIAL: 'FACTORIAL',
    WRAP_PAREN: 'WRAP_PAREN',
    COS: 'COS',
    SIN: 'SIN',
    TAN: 'TAN',
    SINH: 'SINH',
    COSH: 'COSH',
    TANH: 'TANH',
    ABS: 'ABS',
    LOG: 'LOG',
    LG: 'LG',
    LOG_BASE_B: 'LOG_BASE_B',
    I: 'I',
    CLEAR: 'CLEAR',
}

export default CALC_OPERATION;
